#!/bin/bash
echo "ALX"
^C
root@8b34b7a001e1:/alx-pre_course/0x01-git/bash# clear
root@8b34b7a001e1:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
echo "School"
^C
root@8b34b7a001e1:/alx-pre_course/0x01-git/bash# git add .
root@8b34b7a001e1:/alx-pre_course/0x01-git/bash# git commit -m "Starting to code today so cool"
#!/bin/bash
echo "ALX" 
